### ISSUE TITLE
Manque valeur dans sensor.defi_hilo?

### ISSUE THREAD

**Issue by Smitters1501** [Eradash/ha-hilo-blueprints#12]
Le sensor a ajouté ne permet pas d'être en état "appreciation".
Je crois qu'il manque la valeur "scheduled" dans l'état du Sensor créer dans configuration.yaml car lorsqu'un défi est planifié, entre 13h et 15h, l'état du Sensor devient "ref_appreciation".
Ainsi, je crois qu'il faut ajouter l'état "scheduled" comme suit: 

```
template:
  - sensor:
      - name: Senseur de défi en cours 2
        state: "{{ is_state('sensor.defi_hilo', ['appreciation','pre_heat','reduction','scheduled']) }}"
```
Aussi, je doute que l'état "appreciation" soit un état valide pour ce sensor.?
Merci
